#!/bin/bash
set -eux

# create a directory for the database files
PGDATA=${PGDATA:-$CONDA_DIR/pgsql}
if [ ! -d "$PGDATA" ]; then
  initdb -D "$PGDATA" --auth-host=md5 --encoding=UTF8
fi

# start the postgres server
pg_ctl -D "$PGDATA" -l "$PGDATA/pgsql.log" start

# copy the initialisation files into the final container
mv init_db $CONDA_DIR/
chmod +x $CONDA_DIR/setup_postgres/init_postgres.sh
$CONDA_DIR/setup_postgres/init_postgres.sh

#Put an equivalent of the above in a config file: init_db.sql
#psql -U postgres postgres -f init_db.sql
#psql test < seed_db.sql

# shut down the postgres server to prevent locks from a dirty shutdown
pg_ctl -D "$PGDATA" -l "$PGDATA/pgsql.log" stop